// <auto-generated>
// Rewired Constants
// This list was generated on 1/29/2021 4:21:59 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
        public const int MoveHorizontal = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Vertical")]
        public const int MoveVertical = 7;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UICancel")]
        public const int UICancel = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UISubmit")]
        public const int UISubmit = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIVertical")]
        public const int UIVertical = 3;
    }
}
